APImail: '' # provide API mail (optional but recommended)
APIkey: '' # provide API key (optional but recommended)
ExperimentName: 'ToyExample'
SampleName: 'PXD014913_Cowpox_Minimal_Example'
HostName: 'human'
ReferenceDBName: 'minRefSeqViral'
ScientificHostName: '"homo sapiens"'
FilterSpectra: False
AddHostandCrapToDB: True

SamplePath: '/home/ziska/code/UIforPepGM/resources/SampleData/spectrafile_PXD014913_cowpox_minimal_example.mgf' # replace  path
ParametersFile: '/home/ziska/code/UIforPepGM/resources/SampleData/parfile_searchgui_PXD014913_cowpox_minimal_example.par' # replace path
DataDir: 'resources/SampleData/'
DatabaseDir: 'resources/Database/'
PeptideShaker: '/home/ziska/code/UIforPepGM/bin/PeptideShaker-2.2.16/PeptideShaker-2.2.16.jar' # replace path
SearchGUI: '/home/ziska/code/UIforPepGM/bin/SearchG1UI-4.1.23/SearchGUI-4.1.23.jar' # replace path
ResourcesDir: 'resources/'
ResultsDir: 'results/'
TaxidMapping: 'taxidMapping/'

searchengines: '-xtandem'
psmFDR: '5.0'
peptideFDR: '5.0'
proteinFDR: '5.0'
TaxaInPlot: 15

Alpha: [0.01,0.05,0.10,0.20,0.40,0.60]
Beta: [0.01,0.05,0.10,0.20,0.40,0.50,0.70]
prior: [0.10,0.30,0.50]