APIkey: 2a1c4ba4755da2d72691d5a6198b22712408
APImail: franziska.kistner@bam.de
AddHostandCrapToDB: false
Alpha: [0.01, 0.05, 0.1, 0.2, 0.4, 0.6]
Beta: [0.01, 0.05, 0.1, 0.2, 0.4, 0.5, 0.7]
DataDir: resources/SampleData/
DatabaseDir: resources/Database/
ExperimentName: ToyExample
FilterSpectra: false
HostName: human
ParametersFile: /home/fkistner/pepgm-gui/pepgm-gui/resources/SampleData/parfile_searchgui_PXD014913_cowpox_minimal_example.par
PeptideShaker: /home/fkistner/pepgm-gui/pepgm-gui/bin/PeptideShaker-2.2.16/PeptideShaker-2.2.16.jar
ReferenceDBName: minRefSeqViral
ResourcesDir: resources/
ResultsDir: results/
SampleName: PXD014913_Cowpox_Minimal_Example
SamplePath: /home/fkistner/pepgm-gui/pepgm-gui/resources/SampleData/spectrafile_PXD014913_cowpox_minimal_example.mgf
ScientificHostName: '"homo sapiens"'
SearchGUI: /home/fkistner/pepgm-gui/pepgm-gui/bin/SearchGUI-4.1.23/SearchGUI-4.1.23.jar
TaxaInPlot: 15
TaxidMapping: taxidMapping/
nCores: '8'
nTaxa: '15'
peptideFDR: '5'
prior: [0.1, 0.3, 0.5]
proteinFDR: '5'
psmFDR: '1'
searchengines: -andromeda
